version: "3.8"

services:
  app:
    container_name: 7-solutions-test-golang
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb://admin:password@mongo:27017
      - MONGODB_DBNAME=7-solotions
      - MONGODB_COLLECTION=user
      - DELAY_SECOND=10
      - JWT_SECRET=test-jwt
      - JWT_TIME_EXPIRED_SECOND=3600
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
    driver: local
